/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeedPost {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
}
export interface FriendRequest {
  'to' : Principal,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'from' : Principal,
  'timestamp' : Time,
}
export type Genre = { 'metal' : null } |
  { 'grunge' : null } |
  { 'other' : string } |
  { 'punk' : null } |
  { 'rock' : null } |
  { 'hardcore' : null } |
  { 'indie' : null } |
  { 'alternative' : null };
export interface Report {
  'reportedPost' : [] | [bigint],
  'reportedUser' : [] | [Principal],
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'favoriteBands' : Array<string>,
  'isAgeVerified' : boolean,
  'favoriteGenres' : Array<Genre>,
  'avatarUrl' : [] | [string],
  'location' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createPost' : ActorMethod<[string], bigint>,
  'deleteOwnAccount' : ActorMethod<[], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<FeedPost>>,
  'getFriends' : ActorMethod<[Principal], Array<Principal>>,
  'getPendingRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getReports' : ActorMethod<[], Array<[bigint, Array<Report>]>>,
  'getUserPosts' : ActorMethod<[Principal], Array<FeedPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'reportContent' : ActorMethod<
    [[] | [Principal], [] | [bigint], string],
    undefined
  >,
  'respondToFriendRequest' : ActorMethod<[Principal, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyAgeAndCreateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];