/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Genre = IDL.Variant({
  'metal' : IDL.Null,
  'grunge' : IDL.Null,
  'other' : IDL.Text,
  'punk' : IDL.Null,
  'rock' : IDL.Null,
  'hardcore' : IDL.Null,
  'indie' : IDL.Null,
  'alternative' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'favoriteBands' : IDL.Vec(IDL.Text),
  'isAgeVerified' : IDL.Bool,
  'favoriteGenres' : IDL.Vec(Genre),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const FeedPost = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
});
export const FriendRequest = IDL.Record({
  'to' : IDL.Principal,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'from' : IDL.Principal,
  'timestamp' : Time,
});
export const Report = IDL.Record({
  'reportedPost' : IDL.Opt(IDL.Nat),
  'reportedUser' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createPost' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteOwnAccount' : IDL.Func([], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
  'getFriends' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Principal)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getReports' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Report)))],
      ['query'],
    ),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(FeedPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'reportContent' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat), IDL.Text],
      [],
      [],
    ),
  'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
  'verifyAgeAndCreateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Genre = IDL.Variant({
    'metal' : IDL.Null,
    'grunge' : IDL.Null,
    'other' : IDL.Text,
    'punk' : IDL.Null,
    'rock' : IDL.Null,
    'hardcore' : IDL.Null,
    'indie' : IDL.Null,
    'alternative' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'favoriteBands' : IDL.Vec(IDL.Text),
    'isAgeVerified' : IDL.Bool,
    'favoriteGenres' : IDL.Vec(Genre),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const FeedPost = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
  });
  const FriendRequest = IDL.Record({
    'to' : IDL.Principal,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'from' : IDL.Principal,
    'timestamp' : Time,
  });
  const Report = IDL.Record({
    'reportedPost' : IDL.Opt(IDL.Nat),
    'reportedUser' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createPost' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteOwnAccount' : IDL.Func([], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
    'getFriends' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getReports' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(Report)))],
        ['query'],
      ),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(FeedPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'reportContent' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat), IDL.Text],
        [],
        [],
      ),
    'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
    'verifyAgeAndCreateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };